name: llm
channels:
  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.11.14
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - airportsdata==20250909
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - astor==0.8.1
      - attrs==25.4.0
      - blake3==1.0.8
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - compressed-tensors==0.9.1
      - cupy-cuda12x==13.6.0
      - datasets==4.4.1
      - deepspeed==0.18.3
      - depyf==0.18.0
      - dill==0.4.0
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.8.0
      - einops==0.8.1
      - email-validator==2.3.0
      - fastapi==0.124.2
      - fastapi-cli==0.0.16
      - fastapi-cloud-cli==0.6.0
      - fastar==0.8.0
      - fastrlock==0.8.3
      - filelock==3.19.1
      - flash-attn==2.8.3
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gguf==0.10.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - hjson==3.1.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - importlib-metadata==8.7.0
      - iniconfig==2.3.0
      - interegular==0.3.3
      - jinja2==3.1.6
      - jiter==0.12.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - lark==1.2.2
      - llvmlite==0.43.0
      - lm-format-enforcer==0.10.12
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - mistral-common==1.8.6
      - mpmath==1.3.0
      - msgpack==1.1.2
      - msgspec==0.20.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - nest-asyncio==1.6.0
      - networkx==3.5
      - ninja==1.13.0
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - nvitop==1.6.1
      - openai==2.11.0
      - opencv-python-headless==4.11.0.86
      - outlines==0.1.11
      - outlines-core==0.1.26
      - packaging==25.0
      - pandas==2.3.3
      - partial-json-parser==0.2.1.1.post7
      - pillow==11.3.0
      - pluggy==1.6.0
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.4.1
      - protobuf==6.33.2
      - psutil==7.1.3
      - py-cpuinfo==9.0.0
      - pyarrow==22.0.0
      - pybind11==3.0.1
      - pycountry==24.6.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-extra-types==2.10.6
      - pygments==2.19.2
      - pytest==9.0.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - ray==2.40.0
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - rich==14.2.0
      - rich-toolkit==0.17.0
      - rignore==0.7.6
      - rpds-py==0.30.0
      - safetensors==0.7.0
      - sentencepiece==0.2.1
      - sentry-sdk==2.47.0
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.50.0
      - sympy==1.13.1
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - torch==2.5.1+cu124
      - torch-c-dlpack-ext==0.1.4
      - torchaudio==2.5.1+cu124
      - torchvision==0.20.1+cu124
      - tqdm==4.67.1
      - transformers==4.57.3
      - triton==3.1.0
      - trl==0.26.0
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.6.2
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - vllm==0.7.3
      - watchfiles==1.1.1
      - websockets==15.0.1
      - xformers==0.0.28.post3
      - xgrammar==0.1.11
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /root/anaconda3/envs/llm
